#!/usr/bin/env bash
# A Bash script that accepts one argument
new_user="$1"
adduser --gecos "" --disabled-password --quiet "$new_user"
# Use the sudo -u command to execute a command as another user
sudo -u "$new_user" whoami
